root: true
plugins:
  - '@typescript-eslint'
  - promise
extends:
  - airbnb
  - airbnb-typescript
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:promise/recommended
  - prettier
rules:
  import/prefer-default-export: off
  import/extensions: off
  import/no-extraneous-dependencies: off
  no-restricted-exports: off
  no-use-before-define: off
  react/react-in-jsx-scope: off
  react-hooks/exhaustive-deps: off
  react/require-default-props: off
  react/jsx-props-no-spreading: off
  promise/catch-or-return: off
  '@typescript-eslint/no-floating-promises': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-use-before-define':
    - error
    - functions: false
      classes: true
      variables: true
      typedefs: true

parser: '@typescript-eslint/parser'
parserOptions:
  tsconfigRootDir: ./
  project:
    - ./tsconfig.json

env:
  browser: true
  es2021: true
  node: true
  jest: true
