root: true
plugins:
  - '@typescript-eslint'
  - promise
  - unicorn
extends:
  - airbnb
  - airbnb-typescript
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:promise/recommended
  - plugin:unicorn/recommended
  - prettier
rules:
  import/prefer-default-export: off
  react/react-in-jsx-scope: off
  unicorn/prevent-abbreviations: off
  unicorn/no-array-for-each: off
  import/no-extraneous-dependencies: off
  no-use-before-define: off
  unicorn/prefer-module: off
  unicorn/filename-case:
    - error
    - cases:
        camelCase: true
        pascalCase: true
      ignore:
        - vite-env.d.ts
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-use-before-define':
    - error
    - functions: false
      classes: true
      variables: true
      typedefs: true

parser: '@typescript-eslint/parser'
parserOptions:
  tsconfigRootDir: ./
  project:
    - ./tsconfig.json

overrides:
  - files:
      - '*.js'
    rules:
      '@typescript-eslint/no-var-requires': off
      unicorn/prefer-module: off
  - files:
      - '**/__tests__/**/*.[jt]s?(x)'
      - '**/?(*.)+(spec|test).[jt]s?(x)'
    extends:
      - plugin:testing-library/react

env:
  browser: true
  es2021: true
  node: true
  jest: true
