yarnPath: .yarn/releases/yarn-3.2.2.cjs
nodeLinker: pnpm

packageExtensions:
  vite-plugin-style-import@*:
    dependencies:
      consola: '*'

  postcss-scss@*:
    dependencies:
      postcss: ^8.3.3

  app-builder-lib@*:
    dependencies:
      dmg-builder: 23.4.0
