yarnPath: .yarn/releases/yarn-3.2.2.cjs
nodeLinker: pnp

packageExtensions:
  vite-plugin-style-import@*:
    dependencies:
      consola: "*"

  jest-config@*:
    dependencies:
      ts-node: ">=9.0.0"
