nodeLinker: pnp

packageExtensions:
  "@testing-library/user-event@*":
    dependencies:
      "@testing-library/dom": ">=7.21.4"
  postcss-scss@*:
    dependencies:
      postcss: ^8.3.3
  vite-plugin-style-import@*:
    dependencies:
      consola: "*"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
