yarnPath: .yarn/releases/yarn-3.2.2.cjs
nodeLinker: pnpm

packageExtensions:
  vite-plugin-style-import@*:
    dependencies:
      consola: '*'

  '@testing-library/user-event@*':
    dependencies:
      '@testing-library/dom': '>=7.21.4'

  postcss-scss@*:
    dependencies:
      postcss: ^8.3.3

  app-builder-lib@*:
    dependencies:
      dmg-builder: 23.4.0
